/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\sphinx.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function Sphinx(props) {
  const { nodes, materials } = useGLTF('../../public/models/sphinx.glb')
    /** Textures*/
    const tPath = "../../public/textures/"
    const sphinxTextures = useTexture({
      map: tPath+"Wall_Stone_Hieroglyphs_001_basecolor.jpg",
      aoMap: tPath+"Wall_Stone_Hieroglyphs_001_ambientOcclusion.jpg",
      roughnessMap: tPath+"Wall_Stone_Hieroglyphs_001_roughness.jpg",
      displacementMap: tPath+"Wall_Stone_Hieroglyphs_001_height.png",
      normalMap: tPath+"Wall_Stone_Hieroglyphs_001_normal.jpg"
    });
    console.log(materials.Regular)
    materials.Regular.map = sphinxTextures.map;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={materials.Regular} rotation={[-Math.PI / 2, 0, 0]}>
      </mesh>

    </group>
  )
}

useGLTF.preload('../../public/models/sphinx.glb')
